This fixes
```
java.lang.IllegalArgumentException: Not a valid (absolute) URI: oa for entity with roles: [RDFObjectImpl, TextPositionSelector, T
extPositionQuoteSelector, TextQuoteSelector, ResourceObject]
        at org.openrdf.repository.object.composition.ClassResolver.resolveRoles(ClassResolver.java:175) ~[mico-extractor-named-entity-recognizer.jar:na]
```
as the @Iri annotation was pointing to the namespace prefix `oa` instead of the URI of the oa:prefix property.